### ISSUE TITLE
Source code for ret2csu

### ISSUE THREAD

**Issue by varshavraju** [guyinatuxedo/nightmare#20]
There is no source code for ret2csu binary. There is only pseudo code of a function.
Requesting to share complete source code for binary ret2csu.

**Comment by guyinatuxedo** [comment]
Thank you for the issue. This challenge I did not create, and from the looks of it, I'm not going to be able to get source code for it. I believe I got it from https://ropemporium.com/challenge/ret2csu.html. So I don't have source code to give out. Sorry I couldn't be of more help, have a nice day!
