### ISSUE TITLE
GDB cheat sheet link is missing

### ISSUE THREAD

**Issue by m3moryleak** [guyinatuxedo/nightmare#25]
There's a missing link in the section called [1.4. Debugging with GDB](https://guyinatuxedo.github.io/02-intro_tooling/gdb-gef/index.html) , exactly at the title named : [Running](https://guyinatuxedo.github.io/02-intro_tooling/gdb-gef/index.html#running) 

>  The most common breakpoint to set is on main, which we can set with 'break main' or 'b main'. Most GDB commands can be shortened. Check out this cheat sheet for more:

**Comment by SmoothHacker** [comment]
We'll attach a cheat sheet in a later update.

**Comment by PinkDraconian** [comment]
Noticed this cheat cheet is still missing.
