### ISSUE TITLE
1.6.2. Helithumper RE - Can't find the binary

### ISSUE THREAD

**Issue by IdanBanani** [guyinatuxedo/nightmare#30]
nightmare/modules/03-beginner_re/helithumper_re/readme.md

```
"This was a challenge made by Helithumper (github.com/helithumper). Let's take a look at the binary:

$    ./rev

```
couldn't find it ...

**Comment by SmoothHacker** [comment]
Binary is located [here](https://github.com/guyinatuxedo/nightmare/blob/master/modules/03-beginner_re/helithumper_re/rev) along side the readme file in the repo
