### ISSUE TITLE
Can't see the stack variables in ghidra

### ISSUE THREAD

**Issue by 0xtensho** [guyinatuxedo/nightmare#49]
You said [here](https://guyinatuxedo.github.io/04-bof_variable/csaw18_boi/index.html) that you just needed to double click on a variabale to see the stack frame but that doesn't work in ghidra.

**Comment by mnemo9** [comment]
you basically double click (or hover) the name of a variable anywhere in a function to get to the top function 'signature' where local variables (passed and stack) are shown.

**Comment by 0xTensho** [comment]
I have ghidra 10.1.2, and the 'Double click' doesn't do anything, right click -> Edit function signature doesn't look like the right thing, and hovering a variable just shows infos about it's type, like int, char,...
