### ISSUE TITLE
Potential bug in 03-beginner_re/helithumper_re

### ISSUE THREAD

**Issue by vilroi** [guyinatuxedo/nightmare#68]
Hey all,

There is a potential issue where the vlidate() function returns a success, even if the whole flag has not been submitted:
```console
vilroi@nightmare:~/nightmare/modules/03-beginner_re/helithumper_re$ ./rev
Welcome to the Salty Spitoon™, How tough are ya?
fl
Right this way...
```
I would like to fix this; is the source of `rev` available somewhere?

I was not able to locate it in Helithumper's github (unless I missed it ofcourse).

Thank you in advance.

**Comment by SmoothHacker** [comment]
There's no source online iirc
